
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/english?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pass
  jpa:
    show-sql: true